parameters:
    env(facebook_consumer_key): ''
    env(facebook_consumer_secret): ''
    env(facebook_redirect_uri): ''
    env(google_consumer_key): ''
    env(google_consumer_secret): ''
    env(google_application_token): ''
    env(google_service_account_email): ''
    env(google_key_file): ''
    env(google_key_password): ''
    env(twitter_consumer_key): ''
    env(twitter_consumer_secret): ''
    env(twitter_application_token): ''
    env(spotify_consumer_key): ''
    env(spotify_consumer_secret): ''
    env(tumblr_consumer_key): ''
    env(tumblr_consumer_secret): ''
    env(tumblr_application_token): ''
    env(steam_application_token): ''
    env(linkedin_consumer_key): ''
    env(linkedin_consumer_secret): ''

hwi_oauth:
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "%env(facebook_consumer_key)%"
            client_secret:       "%env(facebook_consumer_secret)%"

        google:
            type:                google
            client_id:           "%env(google_consumer_key)%"
            client_secret:       "%env(google_consumer_secret)%"

        twitter:
            type:                twitter
            client_id:           "%env(twitter_consumer_key)%"
            client_secret:       "%env(twitter_consumer_secret)%"

        spotify:
            type:                spotify
            client_id:           "%env(spotify_consumer_key)%"
            client_secret:       "%env(spotify_consumer_secret)%"

        tumblr:
            type:                oauth1
            client_id:           "%env(tumblr_consumer_key)%"
            client_secret:       "%env(tumblr_consumer_secret)%"
            user_response_class: HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse
            paths:
                identifier:     response.user.name
                nickname:       response.user.name
                realname:       response.user.name
            access_token_url:   'https://www.tumblr.com/oauth/access_token'
            authorization_url:  'https://www.tumblr.com/oauth/authorize'
            infos_url:          'https://api.tumblr.com/v2/user/info'
            request_token_url:  'https://www.tumblr.com/oauth/request_token'

        linkedin:
            type:                linkedin
            client_id:           "%env(linkedin_consumer_key)%"
            client_secret:       "%env(linkedin_consumer_secret)%"

    # an optional setting to configure a query string parameter which can be used to redirect
    # the user after authentication, e.g. /connect/facebook?_destination=/my/destination will
    # redirect the user to /my/destination after facebook authenticates them.  If this is not
    # set then the user will be redirected to the original resource that they requested, or
    # the base address if no resource was requested.  This is similar to the behaviour of
    # [target_path_parameter for form login](http://symfony.com/doc/2.0/cookbook/security/form_login.html).
    # target_path_parameter: _destination

    # an optional setting to use the HTTP REFERER header to be used in case no
    # previous URL was stored in the session (i.e. no resource was requested).
    # This is similar to the behaviour of
    # [using the referring URL for form login](http://symfony.com/doc/2.0/cookbook/security/form_login.html#using-the-referring-url).
    # use_referer: true

    # here you will add one (or more) configurations for resource owners
    # and other settings you want to adjust in this bundle, just checkout the list below!