parameters:
    env(api_doc_password): ''

security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: ~ }
        users:
            id: security.users_provider
        api_doc_provider:
            memory:
                users:
                    nekuno:
                        password: "%env(api_doc_password)%"
        admin_provider:
            memory:
                users:
                    admin:
                        password: "%env(admin_http_password)%"
        instant_provider:
            memory:
                users:
                    instant:
                        password: "%env(instant_http_password)%"

    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt

    firewalls:
        default:
            pattern: ^/$
            methods: [GET]
            security: false
        api_doc_public:
            pattern: ^/api/doc/public$
            security: false
        api_doc_private:
            pattern: ^/api/.+$
            http_basic:
                provider: api_doc_provider
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            anonymous: true
            pattern: ^/login$
        public_get:
            anonymous: true
            pattern: (^/profile/metadata$)|(^/profile/categories)|(^/profile/tags)|(^/users/available/)|(^/client/)|(^/public/)
            methods: [GET]
        public_post:
            anonymous: true
            pattern: (^/users$)|(^/register)|(^/invitations/token/validate/)|(^/lookUp/webHook$)|(^/users/validate$)$
            methods: [POST]
        preflight:
            anonymous: true
            pattern: ^/.*$
            methods: [OPTIONS]
        instant:
            pattern: ^/instant/.*$
            http_basic:
                provider: instant_provider
        admin:
            pattern: ^/admin/.*$
            http_basic:
                provider: admin_provider
        secured:
            provider: users
            stateless: true
            pattern: ^.*$
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

