<?php

namespace Model\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FetchRegistryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FetchRegistryRepository extends EntityRepository
{
}
