<?php

namespace Model\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserDataStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDataStatusRepository extends EntityRepository
{
}
