api_consumer.config:
    resource_owner:
        twitter:
            class: Http\OAuth\ResourceOwner\TwitterResourceOwner
            client_credential_class: Http\OAuth\ResourceOwner\ClientCredential\TwitterClientCredential
        facebook:
            class: Http\OAuth\ResourceOwner\FacebookResourceOwner
        google:
            class: Http\OAuth\ResourceOwner\GoogleResourceOwner
            client_credential_class: Http\OAuth\ResourceOwner\ClientCredential\GoogleClientCredentialFromLibrary
        google_profile:
            class: Http\OAuth\ResourceOwner\GoogleResourceOwner
            client_credential_class: Http\OAuth\ResourceOwner\ClientCredential\GoogleClientCredentialFromLibrary
        spotify:
            class: Http\OAuth\ResourceOwner\SpotifyResourceOwner
    fetcher:
        twitter:
            class: ApiConsumer\Fetcher\TwitterFetcher
            resourceOwner: twitter
        facebook_links:
            class: ApiConsumer\Fetcher\FacebookLinksFetcher
            resourceOwner: facebook
        facebook_likes:
            class: ApiConsumer\Fetcher\FacebookLikesFetcher
            resourceOwner: facebook
        google:
            class: ApiConsumer\Fetcher\GoogleFetcher
            resourceOwner: google
        google_profile:
            class: ApiConsumer\Fetcher\GoogleProfileFetcher
            resourceOwner: google_profile
        youtube:
            class: ApiConsumer\Fetcher\YoutubeFetcher
            resourceOwner: google
        spotify:
            class: ApiConsumer\Fetcher\SpotifyFetcher
            resourceOwner: spotify
