api_consumer.config:
    resource_owner:
        twitter:
            class: Http\OAuth\ResourceOwner\TwitterResourceOwner
        facebook:
            class: Http\OAuth\ResourceOwner\FacebookResourceOwner
        google:
            class: Http\OAuth\ResourceOwner\GoogleResourceOwner
            client_credential_class: Http\OAuth\ResourceOwner\ClientCredential\GoogleClientCredentialFromLibrary
        spotify:
            class: Http\OAuth\ResourceOwner\SpotifyResourceOwner
    fetcher:
        twitter:
            class: ApiConsumer\Fetcher\TwitterFetcher
            resourceOwner: twitter
        facebook:
            class: ApiConsumer\Fetcher\FacebookFetcher
            resourceOwner: facebook
        google:
            class: ApiConsumer\Fetcher\GoogleFetcher
            resourceOwner: google
        youtube:
            class: ApiConsumer\Fetcher\YoutubeFetcher
            resourceOwner: google
        spotify:
            class: ApiConsumer\Fetcher\SpotifyFetcher
            resourceOwner: spotify
