nodes:
    user:
        label: User
        class: Service\Consistency\UserConsistencyChecker
        relationships:
            profile:
                type: PROFILE_OF
                direction: incoming
                otherNode: Profile
                minimum: 1
                maximum: 1
        properties:
            qnoow_id:
                required: true
                type: integer
            updatedAt:
                required: true
                type: datetime
                maximum: "now"
                minimum: "2010-01-01"