profile:
    description:
        type: textarea
        min: 0
        max: 20000
        label:
            en: 'About me'
            es: 'Sobre mí'
    birthday:
        type: birthday
        required: true
        label:
            en: 'Birthday'
            es: 'Cumpleaños'
        labelFilter:
            en: 'Age'
            es: 'Edad'
    zodiacSign:
        type: choice
        editable: false
        label:
            en: 'Zodiac sign'
            es: 'Signo del zodíaco'
    height:
        type: integer
        min: 50
        max: 300
        label:
            en: 'Height (cm)'
            es: 'Altura (cm)'
    allergy:
        type: text
        min: 0
        max: 255
        label:
            en: 'Allergy'
            es: 'Alergia'
    car:
        type: choice
        label:
            en: 'Car'
            es: 'Coche'
    sons:
        type: choice
        label:
            en: 'Sons'
            es: 'Hijos'
    wantSons:
        type: choice
        label:
            en: 'Do you want to have sons?'
            es: '¿Quieres tener hijos?'
    languages:
        type: text
        min: 0
        max: 255
        label:
            en: 'Languages'
            es: 'Idiomas'
    gender:
        type: choice
        required: true
        label:
            en: 'Gender'
            es: 'Género'
    hairColor:
        type: choice
        label:
            en: 'Hair color'
            es: 'Color de pelo'
    ethnicGroup:
        type: choice
        label:
            en: 'Ethnic group'
            es: 'Grupo Étnico'
    complexion:
        type: choice
        label:
            en: 'Complexion'
            es: 'Complexión'
    eyeColor:
        type: choice
        label:
            en: 'Eyes color'
            es: 'Color ojos'
    allergy:
        type: choice
        label:
            en: 'Have you any allergy?'
            es: '¿Tienes alguna alergia?'
    handicap:
        type: choice
        label:
            en: 'Have you any handicap?'
            es: '¿Tienes alguna discapacidad?'
    civilStatus:
        type: choice
        label:
            en: 'Civil status'
            es: 'Estado civil'
    nationality:
        type: choice
        label:
            en: 'Nationality'
            es: 'Nacionalidad'
    income:
        type: choice
        label:
            en: 'Income'
            es: 'Ingresos'
    car:
        type: choice
        label:
            en: 'Do you have a car?'
            es: '¿Tienes coche?'
    sons:
        type: choice
        label:
            en: 'Do you have sons?'
            es: '¿Tienes hijos?'
    pets:
        type: choice
        label:
            en: 'Do you have pets?'
            es: '¿Tienes mascotas?'
    smoke:
        type: choice
        label:
            en: 'Do you smoke?'
            es: '¿Fumas?'
    alcohol:
        type: choice
        label:
            en: 'Do you drink alcohol?'
            es: '¿Bebes Alcohol?'
    drugs:
        type: choice
        label:
            en: 'Do you take drugs?'
            es: '¿Tomas drogas?'
    diet:
        type: choice
        label:
            en: 'Are you on a special diet?'
            es: '¿Sigues alguna dieta especial?'
    wantSons:
        type: choice
        label:
            en: 'Do you want to have children?'
            es: '¿Quieres tener hijos?'
    orientation:
        type: choice
        label:
            en: 'Orientation'
            es: 'Orientación'
    relationshipInterest:
        type: choice
        label:
            en: 'What are your interests on relations?'
            es: '¿Qué te interesa de las relaciones?'
    dateSmoker:
        type: choice
        label:
            en: 'Would you date a person that smokes?'
            es: '¿Saldrías con una persona que fuma?'
    dateReligion:
        type: choice
        label:
            en: 'Would you date a person with different religious beliefs?'
            es: '¿Saldrías con una persona con diferente creencia religiosa?'
    dateComplexion:
        type: choice
        label:
            en: 'Would you date a person with larger body complexion?'
            es: '¿Saldrías con una persona con mayor complexión?'
    dateAlcohol:
        type: choice
        label:
            en: 'Would you date a person that drinks alcohol?'
            es: '¿Saldrías con una persona que bebe alcohol?'
    dateHandicap:
        type: choice
        label:
            en: 'Will you meet somebody with any disabilities?'
            es: '¿Quedarías con una persona con alguna discapacidad?'
    dateChildren:
        type: choice
        label:
            en: 'Would you date a person with children?'
            es: '¿Saldrías con una persona con hijos?'
    interfaceLanguage:
        type: choice
        required: true
        filterable: false
        label:
            en: 'What interface language do you prefer?'
            es: '¿Qué lenguaje de interfaz prefieres?'
    religion:
        type: tags
        label:
            en: 'Religion'
            es: 'Religión'
    ideology:
        type: tags
        label:
            en: 'Ideology'
            es: 'Ideología'
    profession:
        type: tags
        label:
            en: 'Profession'
            es: 'Profesión'
    education:
        type: tags
        label:
            en: 'Education'
            es: 'Educación'
    location:
        type: location
        required: true
        filterable: false
        label:
            en: 'Location'
            es: 'Ubicación'
