## Doctrine
db.dbname: 'qnoow'
db.user: 'qnoowdev'
db.pass: 'qnoow2014'

## Neo4j
db.neo4j.host: 'qnoow.sb02.stations.graphenedb.com'
db.neo4j.port: 24789
db.neo4j.user: 'qnoow'
db.neo4j.pass: 'jgysJFcDujHaVrdP2DC2'

## Twitter
twitter.consumer_key: 'm9NY9ZghlVeYFVk8fbPp8pp1g'
twitter.consumer_secret: 'yQ5XBabTj1vzCCBVeJoqX9Bli4zcjVWsF6FxHvPtZwkAJseu1l'
